name: Context and expressions
on: [push, workflow_dispatch, pull_request, issues]

jobs:
  get-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: github context
        run: ${{ toJson(github) }}
      - name: runner context
        run: ${{ toJson(runner) }}
      - name: job context
        run: ${{ toJson(job) }}
      - name: secrets context
        run: ${{ toJson(secrets) }}
      - name: steps contexts
        run: ${{ toJson(steps) }}
