name: Pull request
on:
  pull_request:
    branches:
      - "main"

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: run multi line command
        run: |
          node -v
          npm -v

  parallel-run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: check directory
        run: ls -l

  dependent-run-shell-commands:
    runs-on: ubuntu-latest
    needs: [run-shell-commands, parallel-run-shell-commands]
    steps:
      - name: echo path
        run: echo "$PATH"
