name: Pull request
on:
  pull_request:
    branches:
      - "main"

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: run multi line command
        run: |
          pwd
          cd /
          ls
          $GITHUB_SHA
          $GITHUB_REPOSITORY
          $GITHUB_WORKSPACE
          node -v
          npm -v
