name: Pull request
on: [pull_request]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: run multi line command
        run: |
          node -v
          npm -v
