name: Pull request
on:
  pull_request:
    branches:
      - "main"

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: run multi line command
        run: |
          pwd
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          node -v
          npm -v

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: list files in workspace (before)
        run: ls -l
      - name: checkout
        run: |
          git init
          git branch -M main
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git remote -v
          git chekcout main
          git pull
      - name: list files in workspace (after)
        run: ls -l
